services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: warehouse_management:0.0.2  # Custom image name with version tag
    container_name: warehouse_management
    env_file: ./src/.env
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - /volume1/docker/warehouse_management/assets:/warehouse_management/src/assets  # Mount the source code for live development
#      - D:/warehouse_management/assets/:/warehouse_management/src/assets  # Mount the source code for live development

#    command: >
#      sh -c "PYTHONPATH=/app gunicorn src.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000"

  db:
    image: postgres:14
    env_file: ./src/.env
    container_name: postgresql
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - /volume1/docker/warehouse_management/db_data:/var/lib/postgresql/data
#      - D:/warehouse_management/db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    volumes:
      - /volume1/docker/warehouse_management/pgadmin-data:/var/lib/pgadmin
#      - D:/warehouse_management/pgadmin-data:/var/lib/pgadmin
    env_file: ./src/.env
    depends_on:
      - db

  alembic:
    image: warehouse_management:0.0.2
    container_name: alembic
    env_file: ./src/.env
    depends_on:
      - db
#    volumes:
#      - /volume1/docker/warehouse_management/alembic:/warehouse_management/alembic
#      - D:/warehouse_management/alembic:/warehouse_management/alembic
    command: >
      sh -c "alembic revision --autogenerate -m 'Upgrade all tables to v.0.0.2' &&
      alembic upgrade head"

  create_admin:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./src/.env
    depends_on:
      - db
      - app
      - alembic
    command: python -m src.scripts.create_first_admin

#  volumes:
#    postgres_data:
#      driver: local